- job:
    name: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.28
    parent: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1
    vars:
      devstack_localrc:
        MAGNUM_KUBECTL_TAG: v1.28.9
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            magnum:
              labels:
                kube_tag: v1.28.9-rancher1
                container_runtime: containerd
                containerd_version: 1.6.31
                containerd_tarball_sha256: 75afb9b9674ff509ae670ef3ab944ffcdece8ea9f7d92c42307693efa7b6109d
                cloud_provider_tag: v1.27.3
                cinder_csi_plugin_tag: v1.27.3
                k8s_keystone_auth_tag: v1.27.3
                magnum_auto_healer_tag: v1.27.3
                octavia_ingress_controller_tag: v1.27.3
                calico_tag: v3.26.4

- job:
    name: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.28-calico
    parent: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.28
    vars:
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            magnum:
              network_driver: calico

- job:
    name: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.28-flannel
    parent: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.28
    vars:
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            magnum:
              network_driver: flannel

- job:
    name: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.27
    parent: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1
    vars:
      devstack_localrc:
        MAGNUM_KUBECTL_TAG: v1.27.8
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            magnum:
              labels:
                kube_tag: v1.27.8-rancher2
                container_runtime: containerd
                containerd_version: 1.6.28
                containerd_tarball_sha256: f70736e52d61e5ad225f4fd21643b5ca1220013ab8b6c380434caeefb572da9b
                cloud_provider_tag: v1.27.3
                cinder_csi_plugin_tag: v1.27.3
                k8s_keystone_auth_tag: v1.27.3
                magnum_auto_healer_tag: v1.27.3
                octavia_ingress_controller_tag: v1.27.3
                calico_tag: v3.26.4

- job:
    name: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.27-calico
    parent: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.27
    vars:
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            magnum:
              network_driver: calico

- job:
    name: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.27-flannel
    parent: magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.27
    vars:
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            magnum:
              network_driver: flannel

- project:
    queue: magnum
    templates:
      - openstack-cover-jobs
      - openstack-python3-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - magnum-tempest-plugin-tests-api
        - magnum-tempest-plugin-tests-api-jammy
        - magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.27-flannel:
            voting: false
        - magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.27-calico:
            voting: false
        - magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.28-flannel:
            voting: false
        - magnum-tempest-plugin-tests-cluster-k8s_fcos_v1-1.28-calico:
            voting: false
    gate:
      jobs:
        - magnum-tempest-plugin-tests-api
        - magnum-tempest-plugin-tests-api-jammy
