#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

wget -qO- https://get.docker.com/gpg | sudo apt-key add -
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')

# Add the repository
echo "deb https://get.docker.com/${DISTRO} docker main" | \
    sudo tee /etc/apt/sources.list.d/docker.list
