#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/sysconfig/heat-params
    owner: "root:root"
    permissions: "0600"
    content: |
      MESOS_MASTERS_IPS="$MESOS_MASTERS_IPS"
      EXECUTOR_REGISTRATION_TIMEOUT="$EXECUTOR_REGISTRATION_TIMEOUT"
      HTTP_PROXY="$HTTP_PROXY"
      HTTPS_PROXY="$HTTPS_PROXY"
      NO_PROXY="$NO_PROXY"
      AUTH_URL="$AUTH_URL"
      USERNAME="$USERNAME"
      PASSWORD="$PASSWORD"
      TENANT_NAME="$TENANT_NAME"
      VOLUME_DRIVER="$VOLUME_DRIVER"
      REGION_NAME="$REGION_NAME"
      DOMAIN_NAME="$DOMAIN_NAME"
      REXRAY_PREEMPT="$REXRAY_PREEMPT"
      ISOLATION="$ISOLATION"
      WORK_DIR="$WORK_DIR"
      IMAGE_PROVIDERS="$IMAGE_PROVIDERS"
      EXECUTOR_ENVIRONMENT_VARIABLES="$EXECUTOR_ENVIRONMENT_VARIABLES"
