#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/sysconfig/heat-params
    owner: "root:root"
    permissions: "0644"
    content: |
      WAIT_HANDLE="$WAIT_HANDLE"
      ETCD_DISCOVERY_URL="$ETCD_DISCOVERY_URL"
      DOCKER_VOLUME="$DOCKER_VOLUME"
      HTTP_PROXY="$HTTP_PROXY"
      HTTPS_PROXY="$HTTPS_PROXY"
      NO_PROXY="$NO_PROXY"
      SWARM_API_IP="$SWARM_API_IP"
      SWARM_NODE_IP="$SWARM_NODE_IP"
      BAY_UUID="$BAY_UUID"
      USER_TOKEN="$USER_TOKEN"
      MAGNUM_URL="$MAGNUM_URL"
      TLS_DISABLED="$TLS_DISABLED"
      NETWORK_DRIVER="$NETWORK_DRIVER"
      FLANNEL_NETWORK_CIDR="$FLANNEL_NETWORK_CIDR"
      FLANNEL_NETWORK_SUBNETLEN="$FLANNEL_NETWORK_SUBNETLEN"
      FLANNEL_USE_VXLAN="$FLANNEL_USE_VXLAN"
      ETCD_SERVER_IP="$ETCD_SERVER_IP"
      API_IP_ADDRESS="$API_IP_ADDRESS"
