# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems


class V1NFSVolumeSource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        Swagger model

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'server': 'str',
            'path': 'str',
            'read_only': 'bool'
        }

        self.attribute_map = {
            'server': 'server',
            'path': 'path',
            'read_only': 'readOnly'
        }

        self._server = None
        self._path = None
        self._read_only = None

    @property
    def server(self):
        """
        Gets the server of this V1NFSVolumeSource.
        the hostname or IP address of the NFS server; see http://releases.k8s.io/v1.0.4/docs/volumes.md#nfs

        :return: The server of this V1NFSVolumeSource.
        :rtype: str
        """
        return self._server

    @server.setter
    def server(self, server):
        """
        Sets the server of this V1NFSVolumeSource.
        the hostname or IP address of the NFS server; see http://releases.k8s.io/v1.0.4/docs/volumes.md#nfs

        :param server: The server of this V1NFSVolumeSource.
        :type: str
        """
        self._server = server

    @property
    def path(self):
        """
        Gets the path of this V1NFSVolumeSource.
        the path that is exported by the NFS server; see http://releases.k8s.io/v1.0.4/docs/volumes.md#nfs

        :return: The path of this V1NFSVolumeSource.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """
        Sets the path of this V1NFSVolumeSource.
        the path that is exported by the NFS server; see http://releases.k8s.io/v1.0.4/docs/volumes.md#nfs

        :param path: The path of this V1NFSVolumeSource.
        :type: str
        """
        self._path = path

    @property
    def read_only(self):
        """
        Gets the read_only of this V1NFSVolumeSource.
        forces the NFS export to be mounted with read-only permissions; see http://releases.k8s.io/v1.0.4/docs/volumes.md#nfs

        :return: The read_only of this V1NFSVolumeSource.
        :rtype: bool
        """
        return self._read_only

    @read_only.setter
    def read_only(self, read_only):
        """
        Sets the read_only of this V1NFSVolumeSource.
        forces the NFS export to be mounted with read-only permissions; see http://releases.k8s.io/v1.0.4/docs/volumes.md#nfs

        :param read_only: The read_only of this V1NFSVolumeSource.
        :type: bool
        """
        self._read_only = read_only

    def to_dict(self):
        """
        Return model properties dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Return model properties str
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()
