# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems


class V1ServicePort(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        Swagger model

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'protocol': 'str',
            'port': 'int',
            'target_port': 'str',
            'node_port': 'int'
        }

        self.attribute_map = {
            'name': 'name',
            'protocol': 'protocol',
            'port': 'port',
            'target_port': 'targetPort',
            'node_port': 'nodePort'
        }

        self._name = None
        self._protocol = None
        self._port = None
        self._target_port = None
        self._node_port = None

    @property
    def name(self):
        """
        Gets the name of this V1ServicePort.
        the name of this port; optional if only one port is defined

        :return: The name of this V1ServicePort.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this V1ServicePort.
        the name of this port; optional if only one port is defined

        :param name: The name of this V1ServicePort.
        :type: str
        """
        self._name = name

    @property
    def protocol(self):
        """
        Gets the protocol of this V1ServicePort.
        the protocol used by this port; must be UDP or TCP; TCP if unspecified

        :return: The protocol of this V1ServicePort.
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """
        Sets the protocol of this V1ServicePort.
        the protocol used by this port; must be UDP or TCP; TCP if unspecified

        :param protocol: The protocol of this V1ServicePort.
        :type: str
        """
        self._protocol = protocol

    @property
    def port(self):
        """
        Gets the port of this V1ServicePort.
        the port number that is exposed

        :return: The port of this V1ServicePort.
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """
        Sets the port of this V1ServicePort.
        the port number that is exposed

        :param port: The port of this V1ServicePort.
        :type: int
        """
        self._port = port

    @property
    def target_port(self):
        """
        Gets the target_port of this V1ServicePort.
        number or name of the port to access on the pods targeted by the service; defaults to the service port; number must be in the range 1 to 65535; name must be an IANA_SVC_NAME; see http://releases.k8s.io/v1.0.4/docs/services.md#defining-a-service

        :return: The target_port of this V1ServicePort.
        :rtype: str
        """
        return self._target_port

    @target_port.setter
    def target_port(self, target_port):
        """
        Sets the target_port of this V1ServicePort.
        number or name of the port to access on the pods targeted by the service; defaults to the service port; number must be in the range 1 to 65535; name must be an IANA_SVC_NAME; see http://releases.k8s.io/v1.0.4/docs/services.md#defining-a-service

        :param target_port: The target_port of this V1ServicePort.
        :type: str
        """
        self._target_port = target_port

    @property
    def node_port(self):
        """
        Gets the node_port of this V1ServicePort.
        the port on each node on which this service is exposed when type=NodePort or LoadBalancer; usually assigned by the system; if specified, it will be allocated to the service if unused or else creation of the service will fail; see http://releases.k8s.io/v1.0.4/docs/services.md#type--nodeport

        :return: The node_port of this V1ServicePort.
        :rtype: int
        """
        return self._node_port

    @node_port.setter
    def node_port(self, node_port):
        """
        Sets the node_port of this V1ServicePort.
        the port on each node on which this service is exposed when type=NodePort or LoadBalancer; usually assigned by the system; if specified, it will be allocated to the service if unused or else creation of the service will fail; see http://releases.k8s.io/v1.0.4/docs/services.md#type--nodeport

        :param node_port: The node_port of this V1ServicePort.
        :type: int
        """
        self._node_port = node_port

    def to_dict(self):
        """
        Return model properties dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Return model properties str
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()
