#!/usr/bin/env python
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class V1beta3_PodStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'Condition': 'list[v1beta3_PodCondition]',
            
            
            'containerStatuses': 'list[v1beta3_ContainerStatus]',
            
            
            'hostIP': 'str',
            
            
            'message': 'str',
            
            
            'phase': 'str',
            
            
            'podIP': 'str'
            
        }

        self.attributeMap = {
            
            'Condition': 'Condition',
            
            'containerStatuses': 'containerStatuses',
            
            'hostIP': 'hostIP',
            
            'message': 'message',
            
            'phase': 'phase',
            
            'podIP': 'podIP'
            
        }       

        
        #current service state of pod
        
        self.Condition = None # list[v1beta3_PodCondition]
        
        #list of container statuses
        
        self.containerStatuses = None # list[v1beta3_ContainerStatus]
        
        #IP address of the host to which the pod is assigned; empty if not yet scheduled
        
        self.hostIP = None # str
        
        #human readable message indicating details about why the pod is in this condition
        
        self.message = None # str
        
        #current condition of the pod.
        
        self.phase = None # str
        
        #IP address allocated to the pod; routable at least within the cluster; empty if not yet allocated
        
        self.podIP = None # str
        
