#!/usr/bin/env python
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class V1beta3_ContainerStateTerminated(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'containerID': 'str',
            
            
            'exitCode': 'int',
            
            
            'finishedAt': 'str',
            
            
            'message': 'str',
            
            
            'reason': 'str',
            
            
            'signal': 'int',
            
            
            'startedAt': 'str'
            
        }

        self.attributeMap = {
            
            'containerID': 'containerID',
            
            'exitCode': 'exitCode',
            
            'finishedAt': 'finishedAt',
            
            'message': 'message',
            
            'reason': 'reason',
            
            'signal': 'signal',
            
            'startedAt': 'startedAt'
            
        }       

        
        #container&#39;s ID in the format &#39;docker://&lt;container_id&gt;&#39;
        
        self.containerID = None # str
        
        #exit status from the last termination of the container
        
        self.exitCode = None # int
        
        #time at which the container last terminated
        
        self.finishedAt = None # str
        
        #message regarding the last termination of the container
        
        self.message = None # str
        
        #(brief) reason from the last termination of the container
        
        self.reason = None # str
        
        #signal from the last termination of the container
        
        self.signal = None # int
        
        #time at which previous execution of the container started
        
        self.startedAt = None # str
        
