#!/usr/bin/env python
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class V1beta3_ServicePort(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'name': 'str',
            
            
            'port': 'int',
            
            
            'protocol': 'str',
            
            
            'targetPort': 'str'
            
        }

        self.attributeMap = {
            
            'name': 'name',
            
            'port': 'port',
            
            'protocol': 'protocol',
            
            'targetPort': 'targetPort'
            
        }       

        
        #the name of this port; optional if only one port is defined
        
        self.name = None # str
        
        #the port number that is exposed
        
        self.port = None # int
        
        #the protocol used by this port; must be UDP or TCP; TCP if unspecified
        
        self.protocol = None # str
        
        #the port to access on the pods targeted by the service; defaults to the service port
        
        self.targetPort = None # str
        
