#!/usr/bin/env python
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class V1beta3_PersistentVolumeClaimStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'accessModes': 'list[V1beta3_AccessModeType]',
            
            
            'capacity': 'any',
            
            
            'phase': 'str',
            
            
            'volumeRef': 'V1beta3_ObjectReference'
            
        }

        self.attributeMap = {
            
            'accessModes': 'accessModes',
            
            'capacity': 'capacity',
            
            'phase': 'phase',
            
            'volumeRef': 'volumeRef'
            
        }       

        
        #the actual access modes the volume has
        
        self.accessModes = None # list[V1beta3_AccessModeType]
        
        #the actual resources the volume has
        
        self.capacity = None # any
        
        #the current phase of the claim
        
        self.phase = None # str
        
        #a reference to the backing persistent volume, when bound
        
        self.volumeRef = None # V1beta3_ObjectReference
        
