#!/usr/bin/env python
"""
Copyright 2015 Reverb Technologies, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class V1beta3_NodeCondition(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            
            'lastProbeTime': 'str',
            
            
            'lastTransitionTime': 'str',
            
            
            'message': 'str',
            
            
            'reason': 'str',
            
            
            'status': 'str',
            
            
            'type': 'str'
            
        }

        self.attributeMap = {
            
            'lastProbeTime': 'lastProbeTime',
            
            'lastTransitionTime': 'lastTransitionTime',
            
            'message': 'message',
            
            'reason': 'reason',
            
            'status': 'status',
            
            'type': 'type'
            
        }       

        
        #last time the condition was probed
        
        self.lastProbeTime = None # str
        
        #last time the condition transit from one status to another
        
        self.lastTransitionTime = None # str
        
        #human readable message indicating details about last transition
        
        self.message = None # str
        
        #(brief) reason for the condition&#39;s last transition
        
        self.reason = None # str
        
        #status of the condition, one of Full, None, Unknown
        
        self.status = None # str
        
        #type of node condition, one of Ready, Schedulable
        
        self.type = None # str
        
