---
- hosts: all
  roles:
    - configure-swap
    - ensure-docker
  tasks:
    - name: Create logging folders
      file:
        path: "/tmp/logs/{{ item }}"
        state: directory
      with_items:
        - ansible
        - build

    - name: Link logs output folder
      file:
        src: /tmp/logs
        dest: "{{ zuul.project.src_dir }}/logs"
        state: link

    - name: Install python3-docker
      become: true
      package:
        name: python3-docker
        state: present
