#!/bin/sh

echo "START: write-heat-params"

arch=$(uname -m)

case "$arch" in
    aarch64)
        ARCH=arm64
        ;;
    x86_64)
        ARCH=amd64
        ;;
    *)
        ARCH=$arch
        ;;
esac

ssh_cmd="ssh -F /srv/magnum/.ssh/config root@localhost"

# Reconciler delivery — no hardcoded version here. When neither RECONCILER_VERSION
# nor RECONCILER_BINARY_URL is set (the default), the launcher auto-resolves the
# latest published release on every run and upgrades in place, silently falling
# back to the currently-installed binary on any failure. Setting RECONCILER_VERSION
# (or RECONCILER_BINARY_URL) pins an exact build and disables auto-upgrade. The
# last-resort fallback version lives inside install-reconciler-launcher.sh.
RECONCILER_VERSION="${RECONCILER_VERSION:-}"
RECONCILER_BINARY_URL="${RECONCILER_BINARY_URL:-}"
RECONCILER_BINARY_URL_SHA256="${RECONCILER_BINARY_URL_SHA256:-}"
RECONCILER_LOCK_TIMEOUT_SECONDS="${RECONCILER_LOCK_TIMEOUT_SECONDS:-900}"
# Overall reconcile timeout (seconds). Kept below Heat's stack update_timeout
# (default 90m) so the reconciler self-cancels and frees its lock before Heat
# gives up, rather than squatting the lock and wedging every retry.
RECONCILER_RUN_TIMEOUT_SECONDS="${RECONCILER_RUN_TIMEOUT_SECONDS:-4800}"

HEAT_PARAMS=/etc/sysconfig/heat-params
echo "Writing File: $HEAT_PARAMS"
mkdir -p "$(dirname ${HEAT_PARAMS})"
cat << EOF > ${HEAT_PARAMS}
ARCH="$ARCH"
INSTANCE_NAME="$INSTANCE_NAME"
KUBE_ALLOW_PRIV="$KUBE_ALLOW_PRIV"
KUBE_MASTER_IP="$KUBE_MASTER_IP"
KUBE_API_PORT="$KUBE_API_PORT"
KUBE_NODE_PUBLIC_IP="$KUBE_NODE_PUBLIC_IP"
KUBE_NODE_IP="$KUBE_NODE_IP"
ETCD_SERVER_IP="$ETCD_SERVER_IP"
ENABLE_CINDER="$ENABLE_CINDER"
DOCKER_VOLUME="$DOCKER_VOLUME"
DOCKER_VOLUME_SIZE="$DOCKER_VOLUME_SIZE"
DOCKER_STORAGE_DRIVER="$DOCKER_STORAGE_DRIVER"
NETWORK_DRIVER="$NETWORK_DRIVER"
REGISTRY_ENABLED="$REGISTRY_ENABLED"
REGISTRY_PORT="$REGISTRY_PORT"
SWIFT_REGION="$SWIFT_REGION"
REGISTRY_CONTAINER="$REGISTRY_CONTAINER"
REGISTRY_INSECURE="$REGISTRY_INSECURE"
REGISTRY_CHUNKSIZE="$REGISTRY_CHUNKSIZE"
TLS_DISABLED="$TLS_DISABLED"
VERIFY_CA="$VERIFY_CA"
CLUSTER_UUID="$CLUSTER_UUID"
MAGNUM_URL="$MAGNUM_URL"
AUTH_URL="$AUTH_URL"
VOLUME_DRIVER="$VOLUME_DRIVER"
REGION_NAME="$REGION_NAME"
HTTP_PROXY="$HTTP_PROXY"
HTTPS_PROXY="$HTTPS_PROXY"
NO_PROXY="$NO_PROXY"
KUBE_TAG="$KUBE_TAG"
FLANNEL_NETWORK_CIDR="$FLANNEL_NETWORK_CIDR"
PODS_NETWORK_CIDR="$PODS_NETWORK_CIDR"
KUBE_VERSION="$KUBE_VERSION"
TRUSTEE_USER_ID="$TRUSTEE_USER_ID"
TRUSTEE_USERNAME="$TRUSTEE_USERNAME"
TRUSTEE_PASSWORD="$TRUSTEE_PASSWORD"
TRUSTEE_DOMAIN_ID="$TRUSTEE_DOMAIN_ID"
TRUST_ID="$TRUST_ID"
CLOUD_PROVIDER_ENABLED="$CLOUD_PROVIDER_ENABLED"
INSECURE_REGISTRY_URL="$INSECURE_REGISTRY_URL"
CONTAINER_INFRA_PREFIX="$CONTAINER_INFRA_PREFIX"
HEAT_CONTAINER_AGENT_TAG="$HEAT_CONTAINER_AGENT_TAG"
DNS_SERVICE_IP="$DNS_SERVICE_IP"
DNS_CLUSTER_DOMAIN="$DNS_CLUSTER_DOMAIN"
KUBELET_OPTIONS="$KUBELET_OPTIONS"
KUBEPROXY_OPTIONS="$KUBEPROXY_OPTIONS"
OCTAVIA_ENABLED="$OCTAVIA_ENABLED"
KUBE_SERVICE_ACCOUNT_KEY="$KUBE_SERVICE_ACCOUNT_KEY"
KUBE_SERVICE_ACCOUNT_PRIVATE_KEY="$KUBE_SERVICE_ACCOUNT_PRIVATE_KEY"
CA_ROTATION_ID="$CA_ROTATION_ID"
AUTO_HEALING_ENABLED="$AUTO_HEALING_ENABLED"
AUTO_HEALING_CONTROLLER="$AUTO_HEALING_CONTROLLER"
NODEGROUP_ROLE="$NODEGROUP_ROLE"
NODEGROUP_NAME="$NODEGROUP_NAME"
NODE_LABELS="$NODE_LABELS"
NODE_TAINTS="$NODE_TAINTS"
USE_PODMAN="$USE_PODMAN"
CONTAINER_RUNTIME="$CONTAINER_RUNTIME"
OS_AUTOUPGRADE_ENABLED="$OS_AUTOUPGRADE_ENABLED"
RECONCILER_VERSION="${RECONCILER_VERSION}"
RECONCILER_BINARY_URL="${RECONCILER_BINARY_URL}"
RECONCILER_BINARY_URL_SHA256="${RECONCILER_BINARY_URL_SHA256}"
RECONCILER_LOCK_TIMEOUT_SECONDS="${RECONCILER_LOCK_TIMEOUT_SECONDS}"
RECONCILER_RUN_TIMEOUT_SECONDS="${RECONCILER_RUN_TIMEOUT_SECONDS}"
EOF

chown root:root "${HEAT_PARAMS}"
chmod 600 "${HEAT_PARAMS}"

echo "END: write-heat-params"
