---
name: Tag & Release
'on':
  push:
    branches:
      - stackhpc/yoga
permissions:
  actions: read
  contents: write
jobs:
  tag-and-release:
    uses: stackhpc/.github/.github/workflows/tag-and-release.yml@main
